basePath: /
definitions:
  Employee:
    properties:
      id:
        type: int
      name:
        type: string
      salary:
        type: int
    type: object
info:
  contact:
    name: Employee API 
  description: Employee API documentation
  termsOfService: http://swagger.io/terms/
  title: Employee API
  version: "1.0"
  schemes:
  - http
  - https
paths:
  /employees:
    get:
      consumes:
      - application/json
      security:
       - Bearer: []
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Employee'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      tags:
      - Employee 
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
swagger: "2.0"